# docker-compose.yml
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8090:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/samurai
      SPRING_DATASOURCE_USERNAME: samurai
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: samurai
      POSTGRES_USER: samurai
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_datapostgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: