
spring:
  jpa:
    properties:
      hibernate:
        default_schema: public

  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

  datasource:
    url: jdbc:postgresql://db:5433/samurai
    username: samurai
    password: password
    driver-class-name: org.postgresql.Driver

  docker:
    compose:
      file: src/docker/compose.yaml
      enabled: true
      lifecycle-management: start_only


server:
  port: 8080