spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/samurai
    username: samurai
    password: password

  jpa:
    properties:
      hibernate:
        default_schema: public


  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration


  docker:
    compose:
      file: src/docker/compose.yaml
      enabled: true
      lifecycle-management: start_only