version: '3.8'

services:
  postgres:
    container_name: samurai_db
    image: 'postgres:17'
    environment:
      - 'POSTGRES_DB=samurai'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=samurai'
    ports:
      - '5433:5432'
    networks:
      - samurai-network

  sonar:
    container_name: samurai-sonarqube
    image: sonarqube:10.3.0-community
    environment:
      - SONAR_FORCE_AUTHENTICATION=false
    ports:
      - "127.0.0.1:9001:9000"
      - "127.0.0.1:9000:9000"
    networks:
      - samurai-network

  jenkins:
    container_name: samurai-jenkins
    image: jenkins/jenkins:lts
    privileged: true  # Required for Docker in Docker
    user: root
    environment:
      - JENKINS_OPTS=--httpPort=8080
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # Mount Docker socket
      - /usr/local/bin/docker:/usr/local/bin/docker  # Mount Docker binary
    networks:
      - samurai-network

networks:
  samurai-network:
    driver: bridge

volumes:
  jenkins_home: